# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/surface/eos_emulator/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/surface/eos_emulator

PRODUCT_COPY_FILES += \
    vendor/surface/eos_emulator/proprietary/vendor/bin/bc:$(TARGET_COPY_OUT_VENDOR)/bin/bc \
    vendor/surface/eos_emulator/proprietary/vendor/bin/createns:$(TARGET_COPY_OUT_VENDOR)/bin/createns \
    vendor/surface/eos_emulator/proprietary/vendor/bin/devmem:$(TARGET_COPY_OUT_VENDOR)/bin/devmem \
    vendor/surface/eos_emulator/proprietary/vendor/bin/dhcpclient:$(TARGET_COPY_OUT_VENDOR)/bin/dhcpclient \
    vendor/surface/eos_emulator/proprietary/vendor/bin/dhcpserver:$(TARGET_COPY_OUT_VENDOR)/bin/dhcpserver \
    vendor/surface/eos_emulator/proprietary/vendor/bin/dumpsys:$(TARGET_COPY_OUT_VENDOR)/bin/dumpsys \
    vendor/surface/eos_emulator/proprietary/vendor/bin/execns:$(TARGET_COPY_OUT_VENDOR)/bin/execns \
    vendor/surface/eos_emulator/proprietary/vendor/bin/fsync:$(TARGET_COPY_OUT_VENDOR)/bin/fsync \
    vendor/surface/eos_emulator/proprietary/vendor/bin/getconf:$(TARGET_COPY_OUT_VENDOR)/bin/getconf \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hostapd_nohidl:$(TARGET_COPY_OUT_VENDOR)/bin/hostapd_nohidl \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.fingerprint@2.1-service \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.broadcastradio@1.1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.broadcastradio@1.1-service \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.gnss@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gnss@1.0-service \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.keymaster@3.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@3.0-service \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.power@1.1-service.ranchu:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.power@1.1-service.ranchu \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/android.hardware.thermal@2.0-service.mock:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.thermal@2.0-service.mock \
    vendor/surface/eos_emulator/proprietary/vendor/bin/hw/rild:$(TARGET_COPY_OUT_VENDOR)/bin/hw/rild \
    vendor/surface/eos_emulator/proprietary/vendor/bin/i2cdetect:$(TARGET_COPY_OUT_VENDOR)/bin/i2cdetect \
    vendor/surface/eos_emulator/proprietary/vendor/bin/i2cdump:$(TARGET_COPY_OUT_VENDOR)/bin/i2cdump \
    vendor/surface/eos_emulator/proprietary/vendor/bin/i2cget:$(TARGET_COPY_OUT_VENDOR)/bin/i2cget \
    vendor/surface/eos_emulator/proprietary/vendor/bin/i2cset:$(TARGET_COPY_OUT_VENDOR)/bin/i2cset \
    vendor/surface/eos_emulator/proprietary/vendor/bin/iconv:$(TARGET_COPY_OUT_VENDOR)/bin/iconv \
    vendor/surface/eos_emulator/proprietary/vendor/bin/install:$(TARGET_COPY_OUT_VENDOR)/bin/install \
    vendor/surface/eos_emulator/proprietary/vendor/bin/ipv6proxy:$(TARGET_COPY_OUT_VENDOR)/bin/ipv6proxy \
    vendor/surface/eos_emulator/proprietary/vendor/bin/iw:$(TARGET_COPY_OUT_VENDOR)/bin/iw \
    vendor/surface/eos_emulator/proprietary/vendor/bin/nc:$(TARGET_COPY_OUT_VENDOR)/bin/nc \
    vendor/surface/eos_emulator/proprietary/vendor/bin/netcat:$(TARGET_COPY_OUT_VENDOR)/bin/netcat \
    vendor/surface/eos_emulator/proprietary/vendor/bin/netmgr:$(TARGET_COPY_OUT_VENDOR)/bin/netmgr \
    vendor/surface/eos_emulator/proprietary/vendor/bin/nproc:$(TARGET_COPY_OUT_VENDOR)/bin/nproc \
    vendor/surface/eos_emulator/proprietary/vendor/bin/nsenter:$(TARGET_COPY_OUT_VENDOR)/bin/nsenter \
    vendor/surface/eos_emulator/proprietary/vendor/bin/qemu-props:$(TARGET_COPY_OUT_VENDOR)/bin/qemu-props \
    vendor/surface/eos_emulator/proprietary/vendor/bin/unlink:$(TARGET_COPY_OUT_VENDOR)/bin/unlink \
    vendor/surface/eos_emulator/proprietary/vendor/bin/unshare:$(TARGET_COPY_OUT_VENDOR)/bin/unshare \
    vendor/surface/eos_emulator/proprietary/vendor/bin/uuidgen:$(TARGET_COPY_OUT_VENDOR)/bin/uuidgen \
    vendor/surface/eos_emulator/proprietary/vendor/bin/watch:$(TARGET_COPY_OUT_VENDOR)/bin/watch \
    vendor/surface/eos_emulator/proprietary/vendor/etc/fstab.ranchu:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ranchu \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.broadcastradio@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.broadcastradio@1.1-service.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.gnss@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@1.0-service.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.power@1.1-service.ranchu.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power@1.1-service.ranchu.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/init/rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rild.rc \
    vendor/surface/eos_emulator/proprietary/vendor/etc/permissions/com.oema0.eos_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.oema0.eos_v1.xml \
    vendor/surface/eos_emulator/proprietary/vendor/etc/primary_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/primary_audio_policy_configuration.xml \
    vendor/surface/eos_emulator/proprietary/vendor/etc/simulated_hostapd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/simulated_hostapd.conf \
    vendor/surface/eos_emulator/proprietary/vendor/etc/surround_sound_configuration_5_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/surround_sound_configuration_5_0.xml \
    vendor/surface/eos_emulator/proprietary/vendor/etc/vintf/manifest/android.hardware.thermal@2.0-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.thermal@2.0-service.xml \
    vendor/surface/eos_emulator/proprietary/vendor/lib/android.hardware.audio.common-util.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.audio.common-util.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/android.hardware.audio.common@4.0-util.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.audio.common@4.0-util.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/android.hardware.camera.provider@2.4-external.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.camera.provider@2.4-external.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/android.hardware.camera.provider@2.4-legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.camera.provider@2.4-legacy.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/egl/libEGL_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_emulation.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/egl/libEGL_swiftshader.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_swiftshader.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/egl/libGLESv1_CM_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_emulation.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/egl/libGLESv1_CM_swiftshader.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_swiftshader.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/egl/libGLESv2_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_emulation.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/egl/libGLESv2_swiftshader.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_swiftshader.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/android.hardware.gatekeeper@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.gatekeeper@1.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/android.hardware.gnss@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.gnss@1.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.graphics.mapper@2.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/android.hardware.keymaster@3.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.keymaster@3.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/audio.primary.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/audio.primary.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/audio.primary.goldfish_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.goldfish_legacy.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/audio.r_submix.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.r_submix.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/camera.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/fingerprint.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/fingerprint.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/fingerprint.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/fingerprint.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gatekeeper.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gps.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gps.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gralloc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gralloc.goldfish.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.goldfish.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gralloc.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/gralloc.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/hwcomposer.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/power.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/power.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/sensors.eos.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.eos.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/sensors.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/vibrator.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vibrator.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/hw/vulkan.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libGLESv1_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libGLESv1_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libGLESv2_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libGLESv2_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libOpenglCodecCommon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenglCodecCommon.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libOpenglSystemCommon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenglSystemCommon.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/lib_renderControl_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_renderControl_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libgoldfish-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgoldfish-ril.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libkeymaster3device.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster3device.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libopus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libopus.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_amrnb_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_amrnb_common.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_enc_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_enc_common.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_flacdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_flacdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_aacdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_aacdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_aacenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_aacenc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_amrdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_amrdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_amrnbenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_amrnbenc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_amrwbenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_amrwbenc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_avcdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_avcdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_avcenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_avcenc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_flacdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_flacdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_flacenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_flacenc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_g711dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_g711dec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_gsmdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_gsmdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_hevcdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_hevcdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_mp3dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_mp3dec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_mpeg2dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_mpeg2dec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_mpeg4dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_mpeg4dec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_mpeg4enc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_mpeg4enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_opusdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_opusdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_rawdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_rawdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_vorbisdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_vorbisdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_vpxdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_vpxdec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_soft_vpxenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_vpxenc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_softomx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_softomx.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libstagefright_softomx_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_softomx_plugin.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libvorbisidec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvorbisidec.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libvpx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvpx.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/libvulkan_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvulkan_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib/soundfx/libaudiopreprocessing.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libaudiopreprocessing.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/android.hardware.camera.provider@2.4-external.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.camera.provider@2.4-external.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/android.hardware.camera.provider@2.4-legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.camera.provider@2.4-legacy.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/egl/libEGL_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_emulation.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/egl/libEGL_swiftshader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_swiftshader.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/egl/libGLESv1_CM_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_emulation.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/egl/libGLESv1_CM_swiftshader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_swiftshader.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/egl/libGLESv2_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_emulation.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/egl/libGLESv2_swiftshader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_swiftshader.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/android.hardware.gatekeeper@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.gatekeeper@1.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/android.hardware.gnss@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.gnss@1.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/android.hardware.keymaster@3.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.keymaster@3.0-impl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/audio.primary.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/audio.primary.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/audio.primary.goldfish_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.goldfish_legacy.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/audio.r_submix.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.r_submix.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/camera.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/camera.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/fingerprint.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/fingerprint.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gatekeeper.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gps.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gps.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gps.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gps.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gralloc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gralloc.goldfish.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.goldfish.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gralloc.goldfish.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.goldfish.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/gralloc.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/hwcomposer.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/power.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/power.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/sensors.eos.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.eos.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/sensors.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/vibrator.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vibrator.default.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/hw/vulkan.ranchu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vulkan.ranchu.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libGLESv1_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libGLESv1_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libGLESv2_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libGLESv2_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libOpenglCodecCommon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenglCodecCommon.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libOpenglSystemCommon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenglSystemCommon.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/lib_renderControl_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_renderControl_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libgoldfish-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgoldfish-ril.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libkeymaster3device.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster3device.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libkeystore-engine-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeystore-engine-wifi-hidl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libkeystore-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeystore-wifi-hidl.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libpcap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpcap.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/libvulkan_enc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvulkan_enc.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/surface/eos_emulator/proprietary/vendor/lib64/soundfx/libaudiopreprocessing.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libaudiopreprocessing.so

PRODUCT_PACKAGES += \
    VendorLayoutManagerService
